name: Write tweet

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 12 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Update twitter
      run: |-
        python write_tweet.py
      env:
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "twitter-bot@example.com"
        git config --global user.name "twitter-bot"
        git add -A
        git commit -m "Tweet!" || exit 0
        git push
